# Generated by Django 3.0.4 on 2020-03-29 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='tz',
            field=models.CharField(default='Asia/Kolkata', max_length=30),
            preserve_default=False,
        ),
    ]
