# Generated by Django 3.0.4 on 2020-03-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='user_id',
            new_name='user',
        ),
    ]
