# Generated by Django 3.0.4 on 2020-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20200328_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='user_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
